import { customSizeType } from "@/lib/types/neon";

export const sizePresets: customSizeType[] = [
  {
    _id: '1',
    name: 'Custom',
    maxTextLengthPerLine: 5,
    maxLineLength: 1,
    width: 12,
    height: 6,
    price: 1200,
    multicolor: 1600,
    isPopular: true
  }, {
    _id: '2',
    name: 'Custom',
    maxTextLengthPerLine: 9,
    maxLineLength: 1,
    width: 18,
    height: 12,
    price: 2100,
    multicolor: 2600,
  }, {
    _id: '3',
    name: 'Custom',
    maxTextLengthPerLine: 9,
    maxLineLength: 1,
    width: 18,
    height: 6,
    price: 1600,
    multicolor: 2100,
  }, {
    _id: '4',
    name: 'Custom',
    maxTextLengthPerLine: 10,
    maxLineLength: 2,
    width: 18,
    height: 18,
    price: 2500,
    multicolor: 3000,
    isPopular: true
  }, {
    _id: '5',
    name: 'Custom',
    maxTextLengthPerLine: 15,
    maxLineLength: 1,
    width: 24,
    height: 6,
    price: 2100,
    multicolor: 2600
  }, {
    _id: '6',
    name: 'Custom',
    maxTextLengthPerLine: 15,
    maxLineLength: 2,
    width: 24,
    height: 18,
    price: 3500,
    multicolor: 4500,
    isPopular: true
  }, {
    _id: '7',
    name: 'Custom',
    maxTextLengthPerLine: 15,
    maxLineLength: 1,
    width: 24,
    height: 12,
    price: 2500,
    multicolor: 3000
  }, {
    _id: '8',
    name: 'Custom',
    maxTextLengthPerLine: 15,
    maxLineLength: 3,
    width: 24,
    height: 24,
    price: 4500,
    multicolor: 5500,
    isPopular: true
  }, {
    _id: '9',
    name: 'Custom',
    maxTextLengthPerLine: 15,
    maxLineLength: 1,
    width: 36,
    height: 12,
    price: 3500,
    multicolor: 4500
  }, {
    _id: '10',
    name: 'Custom',
    maxTextLengthPerLine: 15,
    maxLineLength: 2,
    width: 36,
    height: 18,
    price: 5000,
    multicolor: 6500,
  }, {
    _id: '11',
    name: 'Custom',
    maxTextLengthPerLine: 15,
    maxLineLength: 3,
    width: 36,
    height: 24,
    price: 6500,
    multicolor: 8000,
  }, {
    _id: '13',
    name: 'Custom',
    maxTextLengthPerLine: 18,
    maxLineLength: 1,
    width: 48,
    height: 12,
    price: 4500,
    multicolor: 5500
  }, {
    _id: '15',
    name: 'Custom',
    maxTextLengthPerLine: 18,
    maxLineLength: 3,
    width: 48,
    height: 24,
    price: 8500,
    multicolor: 10000,
  }, {
    _id: '16',
    name: 'Custom',
    maxTextLengthPerLine: 18,
    maxLineLength: 3,
    width: 48,
    height: 36,
    price: 12000,
    multicolor: 14000,
  }, {
    _id: '14',
    name: 'Custom',
    maxTextLengthPerLine: 18,
    maxLineLength: 3,
    width: 48,
    height: 48,
    price: 17000,
    multicolor: 20000,
  }
]